version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: golivechat
    ports:
      - "3306:3306"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  gochat:
    build: .
    container_name: gochat
    command: sh -c "sleep 10 && ./gochat"
    ports: 
      - "9999:9999"
    environment:
      DSN: "root:@tcp(mysql:3306)/golivechat"
    depends_on:
      - mysql