version: '3'
services:
  app:
    build: .
    ports: 
      - "9999:9999"
    environment:
      - DSN=root:@tcp(db:3306)/golivechat
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: golivechat
    ports:
      - "3306:3306"